image: 'Visual Studio 2017'

branches:
  only:
    - master
    - /^v\d.*$/
    - /^deploy-test(-.*)?$/

configuration:
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - C:\msys64\usr\bin\bash -lc "cd \"%APPVEYOR_BUILD_FOLDER%\" && scripts/appveyor.sh"

artifacts:
  - path: chiaki-dependencies
    name: chiaki-dependencies
deploy:
- provider: GitHub
  description: Dependencies
  auth_token:
    secure: hbZr2Lx0biQ1GDmJtvmXhGWVbSAkUW+hAbzfqmHXJCyjbJJ4XrG8xLATOHeZ+5hM
  artifact: chiaki-dependencies
  force_update: true
  on:
    branch: master


